languageCode = "en-us"
title = "Charles Lee"
theme = "blackburn"
author = "Charles Lee"
copyright = "&copy; 2017. All rights reserved."
paginate = 10
baseURL = "/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = " "
  brand = " "
  googleAnalytics = "UA-38182774-1"
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "January 02, 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"

#  [[menu.main]]
#    name = "Origami"
#    pre = "<i class='fa fa-map-o fa-fw'></i>"
#    weight = 3
#    identifier = "origami"
#    url = "/origami/"

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 99
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.
  github = "charlesjlee"
  linkedin = "charlesleeonline"
  resume = "CharlesLee-resume.pdf"