BaseURL = "https://charlesjlee.com/"
languageCode = "en-us"
title = "Charles Lee"
author = "Charles Lee"
theme = "blackburn"
RelativeURLs = true
CanonifyURLs = true
paginate = 1000

# force Goldmark to render raw HTML, e.g. <sup>
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[indexes]
	tag = "tags"
	topic = "topics"

[Params]
	googleAnalytics = "UA-38182774-1"
	highlightjs = "androidstudio"
	dateFormat = "January 02, 2006"

  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = [
    "css/mathjax.css",
    "css/lightbox.css",
    "css/gridside-main.css",
    "css/custom.css",
  ]

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"

  [[menu.main]]
    name = "Origami"
    pre = "<i class='fa fas fa-map'></i>"
    weight = 3
    identifier = "origami"
    url = "/origami/"

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 99
    identifier = "about"
    url = "/about/"

[social]
  github = "charlesjlee"
  linkedin = "charlesleeonline"